// Physical Examination Sections Component - Shadcn Style
// This file contains the enhanced shadcn-styled examination sections
// To be integrated into ModernMedicalRecordForm.tsx

import { Box, Paper, Typography, Autocomplete, TextField, Chip, Grid2 as Grid } from '@mui/material';

// Component styles for consistent shadcn-like appearance
export const shadcnCardStyles = {
  elevation: 0,
  p: 2.5,
  borderRadius: 2,
  border: '1px solid',
  borderColor: 'divider',
  bgcolor: 'background.paper',
  transition: 'all 0.2s',
  '&:hover': {
    borderColor: 'primary.main',
    boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)'
  }
};

export const iconBoxStyles = {
  width: 36,
  height: 36,
  borderRadius: 1.5,
  bgcolor: 'primary.50',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  mr: 1.5
};

export const chipStyles = {
  fontSize: '0.75rem',
  height: '24px',
  borderColor: 'primary.main',
  color: 'primary.main'
};

export const textFieldStyles = {
  '& .MuiOutlinedInput-root': {
    borderRadius: 1.5,
    fontSize: '0.875rem',
    minHeight: '56px',
    '& fieldset': {
      borderColor: 'divider'
    },
    '&:hover fieldset': {
      borderColor: 'primary.main'
    }
  }
};

// Extended options for each system
export const expandedExaminationOptions = {
  cardiovascular: [
    'Regular rate and rhythm',
    'S1 S2 present',
    'No murmurs',
    'No rubs',
    'No gallops',
    'No S3 or S4',
    'PMI at 5th intercostal space midclavicular line',
    'PMI displaced',
    'Capillary refill <2 seconds',
    'Capillary refill >2 seconds',
    'Peripheral pulses intact 2+ bilaterally',
    'Radial pulses equal',
    'Femoral pulses palpable',
    'Dorsalis pedis pulses palpable',
    'Posterior tibial pulses palpable',
    'No peripheral edema',
    'Pedal edema 1+',
    'Pedal edema 2+',
    'Pedal edema 3+',
    'Pedal edema 4+',
    'JVP not elevated',
    'JVP elevated',
    'No carotid bruits',
    'Carotid bruits present',
    'Heart sounds distant',
    'Tachycardia',
    'Bradycardia',
    'Irregular rhythm',
    'Systolic murmur',
    'Diastolic murmur'
  ],
  respiratory: [
    'Clear to auscultation bilaterally',
    'Breath sounds equal bilaterally',
    'Vesicular breath sounds',
    'No wheezes',
    'No rales/crackles',
    'No rhonchi',
    'Good air movement',
    'Symmetric chest expansion',
    'No accessory muscle use',
    'No retractions',
    'No cyanosis',
    'No tachypnea',
    'No dyspnea',
    'Wheezing present',
    'Bilateral wheezing',
    'Unilateral wheezing',
    'Crackles/rales present',
    'Fine crackles',
    'Coarse crackles',
    'Ronchi present',
    'Diminished breath sounds',
    'Absent breath sounds',
    'Dullness to percussion',
    'Hyperresonance to percussion',
    'Trachea midline',
    'Tactile fremitus normal',
    'Respiratory distress',
    'Use of accessory muscles'
  ],
  gastrointestinal: [
    'Soft',
    'Non-tender',
    'Non-distended',
    'Bowel sounds present in all 4 quadrants',
    'Bowel sounds normoactive',
    'Bowel sounds hyperactive',
    'Bowel sounds hypoactive',
    'Bowel sounds absent',
    'No masses palpable',
    'No hepatosplenomegaly',
    'No hepatomegaly',
    'No splenomegaly',
    'Liver edge palpable',
    'Spleen tip palpable',
    'No rebound',
    'No guarding',
    'No rigidity',
    'Tympanic to percussion',
    'Dull to percussion',
    'Positive fluid wave',
    'Shifting dullness present',
    'McBurney point tender',
    'Murphy sign positive',
    'Rovsing sign positive',
    'Psoas sign positive',
    'Obturator sign positive',
    'Rebound tenderness',
    'Guarding present',
    'Rigidity present',
    'Distended',
    'Masses palpable',
    'Hernia present',
    'Ascites present'
  ],
  neurological: [
    'Alert and oriented x3 (person, place, time)',
    'Alert and oriented x4 (person, place, time, situation)',
    'Glasgow Coma Scale 15/15',
    'Cranial nerves II-XII grossly intact',
    'CN I (Olfactory) intact',
    'CN II (Optic) intact',
    'CN III, IV, VI (Oculomotor, Trochlear, Abducens) intact',
    'CN V (Trigeminal) intact',
    'CN VII (Facial) intact',
    'CN VIII (Vestibulocochlear) intact',
    'CN IX, X (Glossopharyngeal, Vagus) intact',
    'CN XI (Accessory) intact',
    'CN XII (Hypoglossal) intact',
    'Motor strength 5/5 all extremities',
    'Motor strength 4/5',
    'Motor strength 3/5',
    'Motor strength 2/5',
    'Proximal strength intact',
    'Distal strength intact',
    'Deep tendon reflexes 2+ symmetric',
    'DTRs brisk (3+)',
    'DTRs diminished (1+)',
    'DTRs absent',
    'Babinski negative bilaterally',
    'Babinski positive',
    'Sensation intact to light touch',
    'Sensation intact to pinprick',
    'Proprioception intact',
    'Vibration sense intact',
    'Coordination normal',
    'Finger-to-nose intact',
    'Heel-to-shin intact',
    'Rapid alternating movements intact',
    'Gait steady',
    'Gait normal',
    'Romberg negative',
    'Romberg positive',
    'Tandem gait normal',
    'No tremor',
    'Tremor present',
    'No ataxia',
    'Ataxia present',
    'No focal deficits',
    'Focal neurological deficits present'
  ],
  musculoskeletal: [
    'Full range of motion all joints',
    'No joint swelling',
    'No joint effusion',
    'No joint tenderness',
    'No joint deformity',
    'No joint erythema',
    'No joint warmth',
    'Muscle strength normal',
    'Muscle tone normal',
    'No muscle atrophy',
    'No muscle tenderness',
    'Spine straight',
    'No scoliosis',
    'No kyphosis',
    'No lordosis',
    'Cervical ROM intact',
    'Lumbar ROM intact',
    'Shoulder ROM intact',
    'Elbow ROM intact',
    'Wrist ROM intact',
    'Hip ROM intact',
    'Knee ROM intact',
    'Ankle ROM intact',
    'No crepitus',
    'Crepitus present',
    'Joint effusion present',
    'Joint swelling present',
    'Limited range of motion',
    'Antalgic gait',
    'Straight leg raise negative',
    'Straight leg raise positive',
    'Patrick test negative',
    'McMurray test negative',
    'Drawer test negative',
    'Lachman test negative',
    'Bone tenderness',
    'Deformity present'
  ],
  skin: [
    'Warm',
    'Dry',
    'Intact',
    'No rashes',
    'No lesions',
    'Good turgor',
    'Normal moisture',
    'No jaundice',
    'No cyanosis',
    'No pallor',
    'No diaphoresis',
    'Pink',
    'Well-perfused',
    'Rash present',
    'Macular rash',
    'Papular rash',
    'Maculopapular rash',
    'Vesicular rash',
    'Petechiae',
    'Purpura',
    'Ecchymosis',
    'Erythema',
    'Urticaria',
    'Lesions present',
    'Ulcers present',
    'Scars present',
    'Bruising',
    'Lacerations',
    'Abrasions',
    'Poor turgor',
    'Tenting present',
    'Diaphoretic',
    'Mottled',
    'Cool extremities',
    'Jaundiced',
    'Icteric',
    'Cyanotic',
    'Pale',
    'Edema present',
    'Cellulitis',
    'Abscess'
  ]
};

